(() => {
  'use strict';
  const regions=window.SSX_REGIONS, images=window.SSX_IMAGES, sources=window.SSX_SOURCES;
  const dropImages=window.SSX_DROP_IMAGES||{},mountainImages=window.SSX_MOUNTAIN_IMAGES||{};
  const $=id=>document.getElementById(id);
  const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const normalize=s=>s.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[’‘']/g,'').replace(/[-–]/g,' ').trim();
  const state={query:'',continent:'all',region:'all',mountain:'all',content:'all',favoritesOnly:false};
  const continents=['Nordamerika','Südamerika','Europa','Afrika','Asien','Ozeanien','Antarktika','Fiktiv'];
  const contentNames={base:'Hauptspiel',bonus:'PS3-Bonus',dlc:'DLC'};
  const levels=regions.flatMap(r=>Object.entries(r.mountains).flatMap(([mountain,names])=>names.map(name=>({name,mountain,region:r,id:`${r.id}-${normalize(name).replace(/[^a-z0-9]+/g,'-')}`}))));
  const storageKey='ssx-atlas.favorites.v1',recordStorageKey='ssx-atlas.records.v1',backupFormat='ssx-atlas-personal-data';
  let records={};
  const additionalSurvivalIds=new Set(['rockies-wrecking-crew','alaska-invincible','alps-one-step-ahead','alps-hard-currency','alps-wachter','himalayas-the-monster','himalayas-fall-from-grace','himalayas-death-zone','siberia-critical-mass','patagonia-code-blue','patagonia-last-call','patagonia-vengeance','africa-hush','africa-incoming','new-zealand-jack-knife','new-zealand-thunderbird','antarctica-headshot','antarctica-root-down']);
  const legacyLevelIds={'alps-sentinel':'alps-wachter'};
  function isSurvivalLevel(level){return level.region.deadly===level.name||additionalSurvivalIds.has(level.id);}
  function isRaceLevel(level){return level.name!=="The Kid’s Corner";}
  function sanitizeRecords(saved){const clean={};if(!saved||typeof saved!=='object'||Array.isArray(saved))return clean;for(const [storedId,value] of Object.entries(saved)){const id=legacyLevelIds[storedId]||storedId,level=levels.find(l=>l.id===id);if(!level)continue;if(Number.isInteger(value)&&value>=0){if(isRaceLevel(level))clean[id]={raceMs:value};continue;}if(!value||typeof value!=='object'||Array.isArray(value))continue;const entry={};if(isRaceLevel(level)&&Number.isInteger(value.raceMs)&&value.raceMs>=0)entry.raceMs=value.raceMs;if(Number.isInteger(value.survivalCm)&&value.survivalCm>=0&&isSurvivalLevel(level))entry.survivalCm=value.survivalCm;if(Number.isInteger(value.trickPoints)&&value.trickPoints>=0&&value.trickPoints<=999999999)entry[level.name==='Rolling Thunder'?'trickPointsDay':'trickPoints']=value.trickPoints;for(const key of ['trickPointsDay','trickPointsNight'])if(level.name==='Rolling Thunder'&&Number.isInteger(value[key])&&value[key]>=0&&value[key]<=999999999)entry[key]=value[key];if(Object.keys(entry).length)clean[id]=entry;}return clean;}
  function readRecords(){try{records=sanitizeRecords(JSON.parse(window.localStorage.getItem(recordStorageKey)||'{}'));}catch{records={};}}
  function saveRecords(){try{window.localStorage.setItem(recordStorageKey,JSON.stringify(records));return true;}catch{return false;}}
  function formatRace(ms){const total=Math.floor(ms/1000),minutes=Math.floor(total/60),seconds=total%60,centiseconds=Math.floor((ms%1000)/10);return String(minutes).padStart(2,'0')+':'+String(seconds).padStart(2,'0')+','+String(centiseconds).padStart(2,'0');}
  function formatMeters(cm){const whole=Math.floor(cm/100),fraction=String(cm%100).padStart(2,'0');return String(whole).replace(/\B(?=(\d{3})+(?!\d))/g,'.')+','+fraction+' m';}
  function formatPoints(points){return String(points).replace(/\B(?=(\d{3})+(?!\d))/g,'.');}
  function parseRaceInput(raw){const text=raw.trim().replace(/\s/g,'');let minutes,seconds,fraction='';let m=text.match(/^(\d{1,3}):([0-5]?\d)(?:[,.](\d{0,2}))?$/);if(m){minutes=Number(m[1]);seconds=Number(m[2]);fraction=m[3]||'';}else{m=text.match(/^(\d{1,5})(?:[,.](\d{0,2}))?$/);if(!m)return null;const digits=m[1].padStart(4,'0');minutes=Number(digits.slice(0,-2));seconds=Number(digits.slice(-2));fraction=m[2]||'';}if(seconds>59)return null;const cs=Number(fraction.padEnd(2,'0'));const ms=(minutes*60+seconds)*1000+cs*10;return{ms,formatted:formatRace(ms)};}
  function parseMetersInput(raw){const text=raw.trim().replace(/\s/g,'').replace(/m$/i,'');const m=text.match(/^(\d{1,3}(?:\.\d{3})*|\d+)(?:,(\d{0,2}))?$/);if(!m)return null;const whole=Number(m[1].replace(/\./g,'')),fraction=Number((m[2]||'').padEnd(2,'0'));if(!Number.isSafeInteger(whole)||whole>999999)return null;const cm=whole*100+fraction;return{cm,formatted:formatMeters(cm).replace(/ m$/,'')};}
  function parsePointsInput(raw){const text=raw.trim().replace(/[.\s]/g,'');if(!/^\d{1,9}$/.test(text))return null;const points=Number(text);return{points,formatted:formatPoints(points)};}
  function formatShortRace(ms){const total=Math.floor(ms/1000);return String(Math.floor(total/60)).padStart(2,'0')+':'+String(total%60).padStart(2,'0')+','+String(Math.floor((ms%1000)/10)).padStart(2,'0');}
  function timeDisplay(level){const rec=records[level.id]||{};let html='<div class="level-records'+(isSurvivalLevel(level)?' has-survival':'')+(!isRaceLevel(level)?' no-race':'')+'" aria-label="Persönliche Rekorde">';if(isRaceLevel(level))html+='<span class="score-chip score-race" title="Rennen"><b>Rennen</b><span>'+(rec.raceMs===undefined?'00:00,00':formatShortRace(rec.raceMs))+'</span></span>';if(isSurvivalLevel(level))html+='<span class="score-chip score-survival" title="Überleben"><b>Überleben</b><span>'+(rec.survivalCm===undefined?'00.000,00 m':formatMeters(rec.survivalCm))+'</span></span>';if(level.name==='Rolling Thunder')html+='<span class="score-chip score-trick score-trick-double" title="Tricky: Tag und Nacht"><b>Tricky</b><span class="trick-split"><small>Tag</small><strong>'+(rec.trickPointsDay===undefined?'00.000.000':formatPoints(rec.trickPointsDay))+'</strong><small>Pkt.</small></span><span class="trick-split"><small>Nacht</small><strong>'+(rec.trickPointsNight===undefined?'00.000.000':formatPoints(rec.trickPointsNight))+'</strong><small>Pkt.</small></span></span>';else html+='<span class="score-chip score-trick" title="Tricky"><b>Tricky</b><span>'+(rec.trickPoints===undefined?'00.000.000 Pkt.':formatPoints(rec.trickPoints)+' Pkt.')+'</span></span>';html+='</div>';return html;}
  function recordPanel(level){const rec=records[level.id]||{};const race=rec.raceMs===undefined?'':formatShortRace(rec.raceMs),survival=rec.survivalCm===undefined?'':formatMeters(rec.survivalCm).replace(/ m$/,'');let help=(isRaceLevel(level)?'Rennen: 00:00,00 · ':'')+(isSurvivalLevel(level)?'Überleben: 00.000,00 m · ':'')+'Tricky: 00.000.000 Pkt. Leere Felder bleiben unverändert.';let html='<section class="record-panel" aria-label="Persönliche Rekorde für '+escape(level.name)+'"><div class="record-panel-heading"><span class="record-kicker">DEINE PERSÖNLICHEN REKORDE</span><p>'+[isRaceLevel(level)?'Rennen':null,isSurvivalLevel(level)?'Überleben':null,'Tricky'].filter(Boolean).join(' · ')+'</p></div><form class="record-form" data-record-form data-record-level-id="'+level.id+'"><div class="record-fields">';if(isRaceLevel(level))html+='<label class="record-field race-field"><span>Rennen</span><input name="race" data-record-field="raceMs" type="text" inputmode="decimal" placeholder="0053,25" value="'+race+'" aria-label="Rennen: Minuten, Sekunden und Hundertstel"></label>';if(isSurvivalLevel(level))html+='<label class="record-field survival-field"><span>Überleben</span><input name="survival" data-record-field="survivalCm" type="text" inputmode="decimal" placeholder="11876,24" value="'+survival+'" aria-label="Überleben in Metern"></label>';if(level.name==='Rolling Thunder'){const day=rec.trickPointsDay===undefined?'':formatPoints(rec.trickPointsDay),night=rec.trickPointsNight===undefined?'':formatPoints(rec.trickPointsNight);html+='<label class="record-field trick-field"><span>Tricky · Tag</span><input name="tricky-day" data-record-field="trickPointsDay" type="text" inputmode="numeric" placeholder="54333300" value="'+day+'" aria-label="Tricky Punktzahl am Tag"></label><label class="record-field trick-field"><span>Tricky · Nacht</span><input name="tricky-night" data-record-field="trickPointsNight" type="text" inputmode="numeric" placeholder="54333300" value="'+night+'" aria-label="Tricky Punktzahl bei Nacht"></label>';}else{const tricky=rec.trickPoints===undefined?'':formatPoints(rec.trickPoints);html+='<label class="record-field trick-field"><span>Tricky</span><input name="tricky" data-record-field="trickPoints" type="text" inputmode="numeric" placeholder="54333300" value="'+tricky+'" aria-label="Tricky Punktzahl"></label>';}html+='</div><p class="record-help">'+help+(level.name==='Rolling Thunder'?' Bei Rolling Thunder Tag und Nacht getrennt eintragen.':'')+'</p><button type="submit" class="record-save">Rekorde speichern</button><p class="record-status" role="status" aria-live="polite"></p></form></section>';return html;}
  const mountainKey=(regionId,name)=>`${regionId}:${name}`;
  const favoriteNames={
    regions:new Map(regions.map(r=>[r.id,r.name])),
    mountains:new Map(levels.map(l=>[mountainKey(l.region.id,l.mountain),l.mountain]))
  };
  let favorites={regions:new Set(),mountains:new Set()};
  let storageNotice='';
  function readFavorites(){
    try{
      const raw=window.localStorage.getItem(storageKey);
      const saved=raw===null?{}:JSON.parse(raw);
      if(!saved||typeof saved!=='object'||Array.isArray(saved))throw new Error('Invalid favorites');
      for(const kind of ['regions','mountains']){
        favorites[kind]=new Set((Array.isArray(saved[kind])?saved[kind]:[]).filter(id=>typeof id==='string'&&favoriteNames[kind].has(id)));
      }
      storageNotice='';
    }catch(error){
      storageNotice=error instanceof SyntaxError||error.message==='Invalid favorites'
        ?'Die gespeicherten Favoriten konnten nicht gelesen werden. Du kannst sie neu auswählen.'
        :'Speichern ist in diesem Browser nicht verfügbar. Favoriten bleiben nur bis zum Neuladen erhalten.';
    }
  }
  function saveFavorites(){
    try{
      window.localStorage.setItem(storageKey,JSON.stringify({version:1,regions:[...favorites.regions],mountains:[...favorites.mountains]}));
      storageNotice='';
    }catch{
      storageNotice='Favoriten konnten nicht dauerhaft gespeichert werden. Sie bleiben nur bis zum Neuladen erhalten.';
    }
  }
  function star(kind,key,extraClass=''){
    const active=favorites[kind].has(key);
    const name=favoriteNames[kind].get(key);
    const label=`${kind==='regions'?'Region':'Berg'} ${name} ${active?'aus Favoriten entfernen':'als Favorit speichern'}`;
    return `<button type="button" class="favorite-star ${extraClass}" data-favorite-kind="${kind}" data-favorite-key="${escape(key)}" aria-pressed="${active}" aria-label="${escape(label)}" title="${escape(label)}"><span aria-hidden="true">${active?'★':'☆'}</span></button>`;
  }
  function favoritesInfo(message=''){
    const regionCount=favorites.regions.size,mountainCount=favorites.mountains.size;
    $('favorites-filter').setAttribute('aria-pressed',String(state.favoritesOnly));
    $('favorites-count').textContent=regionCount+mountainCount;
    $('favorites-summary').textContent=regionCount+mountainCount
      ?`${regionCount} ${regionCount===1?'Region':'Regionen'} · ${mountainCount} ${mountainCount===1?'Berg':'Berge'} gespeichert`
      :'Noch keine Favoriten gespeichert.';
    $('favorites-status').textContent=storageNotice||message;
    $('favorites-status').classList.toggle('storage-warning',Boolean(storageNotice));
  }
  function toggleFavorite(button){
    const kind=button.dataset.favoriteKind,key=button.dataset.favoriteKey;
    if(!favoriteNames[kind]?.has(key))return;
    const added=!favorites[kind].has(key);
    if(added)favorites[kind].add(key);else favorites[kind].delete(key);
    saveFavorites();
    const inDialog=$('detail').contains(button);
    render();
    // Update the dialog in place so focus and scroll position stay intact.
    $('detail-body').querySelectorAll('[data-favorite-kind]').forEach(b=>{
      const active=favorites[b.dataset.favoriteKind].has(b.dataset.favoriteKey);
      const label=`${b.dataset.favoriteKind==='regions'?'Region':'Berg'} ${favoriteNames[b.dataset.favoriteKind].get(b.dataset.favoriteKey)} ${active?'aus Favoriten entfernen':'als Favorit speichern'}`;
      b.setAttribute('aria-pressed',String(active));b.setAttribute('aria-label',label);b.title=label;b.firstElementChild.textContent=active?'★':'☆';
    });
    const scope=inDialog?$('detail-body'):$('cards');
    const replacement=[...scope.querySelectorAll('[data-favorite-kind]')].find(b=>b.dataset.favoriteKind===kind&&b.dataset.favoriteKey===key);
    (replacement||$('favorites-filter')).focus({preventScroll:true});
    favoritesInfo(`${favoriteNames[kind].get(key)} ${added?'zu Favoriten hinzugefügt.':'aus Favoriten entfernt.'}`);
  }
  readFavorites();readRecords();
  let filtered=[],lastTrigger;
  function highlight(value){const q=state.query.trim();if(!q)return escape(value);const i=value.toLocaleLowerCase().indexOf(q.toLocaleLowerCase());return i<0?escape(value):escape(value.slice(0,i))+'<mark>'+escape(value.slice(i,i+q.length))+'</mark>'+escape(value.slice(i+q.length));}
  function matchesBase(r){return(state.continent==='all'||r.continent===state.continent)&&(state.content==='all'||r.content===state.content);}
  function matches(l){const r=l.region;return matchesBase(r)&&(!state.favoritesOnly||favorites.regions.has(r.id)||favorites.mountains.has(mountainKey(r.id,l.mountain)))&&(state.region==='all'||r.id===state.region)&&(state.mountain==='all'||l.mountain===state.mountain)&&normalize([l.name,l.mountain,r.name,r.gameName,r.country,r.continent,contentNames[r.content]].join(' ')).includes(normalize(state.query));}
  function options(){const available=regions.filter(matchesBase);if(!available.some(r=>r.id===state.region))state.region='all';$('region').innerHTML='<option value="all">Alle Regionen</option>'+available.map(r=>`<option value="${r.id}">${escape(r.name)}</option>`).join('');$('region').value=state.region;const mountains=available.filter(r=>state.region==='all'||r.id===state.region).flatMap(r=>Object.keys(r.mountains)).sort((a,b)=>a.localeCompare(b));if(!mountains.includes(state.mountain))state.mountain='all';$('mountain').innerHTML='<option value="all">Alle Berge</option>'+mountains.map(m=>`<option>${escape(m)}</option>`).join('');$('mountain').value=state.mountain;}
  function navigation(){const values=['all',...continents];$('continents').innerHTML=values.map((c,i)=>`<button type="button" class="continent-button" data-continent="${c}" aria-pressed="${state.continent===c}"><span class="nav-icon" aria-hidden="true">${i===0?'◎':i===8?'◇':'⊙'}</span><span>${c==='all'?'Alle Kontinente':c==='Fiktiv'?'Mt. Eddie / DLC':c}</span><span class="continent-count">${levels.filter(l=>c==='all'||l.region.continent===c).length}</span></button>`).join('');}
  function cacheBusted(url){return `${url}?v=20261008-1`;}
  function picture(r,detail=false){const img=images[r.id];if(!img)return `<div class="fallback-picture">${escape(r.gameName)} · SSX 2012</div>`;return `<img ${detail?'class="detail-picture"':'loading="lazy"'} src="${escape(cacheBusted(img.url))}" alt="${escape(img.caption)}" ${detail?'':'width="640" height="360"'}>`;}
  function gallery(l,r){
    const track=(dropImages[l.id]||[]).map(url=>({url:cacheBusted(url),caption:`${l.name} · Screenshot`})),mountain=(mountainImages[mountainKey(r.id,l.mountain)]||[]).map(url=>cacheBusted(url)),source=images[r.id];
    const photos=track.length?track:mountain.length?mountain.map(url=>({url,caption:`${l.mountain} · Bergansicht`})):source?[{url:source.url,caption:source.caption,source:source.source,credit:true}]:[];
    if(!photos.length)return `<div class="fallback-picture detail-fallback">${escape(r.gameName)} · SSX 2012</div>`;
    const label=track.length?'Screenshot des Levels':mountain.length?'Screenshot des Berges':'Regionsansicht';
    const credit=photos.find(photo=>photo.credit);
    return `<section class="drop-gallery" data-gallery data-level-id="${l.id}" data-gallery-count="${photos.length}" aria-label="${label} für ${escape(l.name)}"><div class="gallery-frame"><img class="detail-picture is-visible" src="${escape(photos[0].url)}" alt="${escape(photos[0].caption||l.name)}" data-gallery-image><span class="gallery-label">${label}</span>${photos.length>1?'<button type="button" class="gallery-control gallery-prev" data-gallery-prev aria-label="Vorheriges Bild">‹</button><button type="button" class="gallery-control gallery-next" data-gallery-next aria-label="Nächstes Bild">›</button>':''}</div><div class="detail-caption"><span data-gallery-caption>${escape(photos[0].caption||l.name)}</span>${photos.length>1?`<span class="gallery-counter" data-gallery-counter>1 / ${photos.length}</span>`:''}${credit?`<a href="${escape(credit.source)}" target="_blank" rel="noopener noreferrer">Bildquelle ↗</a>`:''}</div>${photos.length>1?`<div class="gallery-dots" role="group" aria-label="Bild auswählen">${photos.map((_,i)=>`<button type="button" class="gallery-dot${i===0?' is-active':''}" data-gallery-dot="${i}" aria-label="Bild ${i+1} von ${photos.length} anzeigen" aria-pressed="${i===0}"></button>`).join('')}</div>`:''}</section>`;
  }
  let galleryTransitionTimer;
  function showGallerySlide(index){
    const root=$('detail-body').querySelector('[data-gallery]');if(!root)return;
    const level=levels.find(item=>item.id===root.dataset.levelId);if(!level)return;
    const r=level.region,track=(dropImages[level.id]||[]).map(url=>({url:cacheBusted(url),caption:`${level.name} · Screenshot`})),mountain=(mountainImages[mountainKey(r.id,level.mountain)]||[]).map(url=>cacheBusted(url)),source=images[r.id];
    const photos=track.length?track:mountain.length?mountain.map(url=>({url,caption:`${level.mountain} · Bergansicht`})):source?[{url:source.url,caption:source.caption}]:[];
    if(photos.length<2)return;
    const next=(index+photos.length)%photos.length,photo=photos[next];
    const img=root.querySelector('[data-gallery-image]');
    if(galleryTransitionTimer)clearTimeout(galleryTransitionTimer);
    const reducedMotion=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
    if(reducedMotion){img.src=photo.url;img.alt=photo.caption||level.name;}
    else{img.classList.remove('is-visible');galleryTransitionTimer=setTimeout(()=>{img.src=photo.url;img.alt=photo.caption||level.name;requestAnimationFrame(()=>img.classList.add('is-visible'));galleryTransitionTimer=undefined;},180);}
    root.querySelector('[data-gallery-caption]').textContent=photo.caption||level.name;
    root.querySelector('[data-gallery-counter]').textContent=`${next+1} / ${photos.length}`;
    root.querySelectorAll('[data-gallery-dot]').forEach(dot=>{const active=Number(dot.dataset.galleryDot)===next;dot.classList.toggle('is-active',active);dot.setAttribute('aria-pressed',String(active));});
  }
  let galleryTimer;
  function stopGallery(){if(galleryTimer){clearInterval(galleryTimer);galleryTimer=undefined;}if(galleryTransitionTimer){clearTimeout(galleryTransitionTimer);galleryTransitionTimer=undefined;}}
  function startGallery(){if(galleryTimer){clearInterval(galleryTimer);galleryTimer=undefined;}const root=$('detail-body').querySelector('[data-gallery]');if(!root||Number(root.dataset.galleryCount)<2||window.matchMedia('(prefers-reduced-motion: reduce)').matches)return;galleryTimer=setInterval(()=>{if(document.hidden||!$('detail').open)return;const index=Number(root.querySelector('[data-gallery-counter]').textContent.split(' ')[0]);showGallerySlide(index);},3000);}
  function render(){
    filtered=levels.filter(matches);
    const shown=regions.filter(r=>filtered.some(l=>l.region===r));
    $('result-count').textContent=`${filtered.length} von ${levels.length} Leveln · ${shown.length} ${shown.length===1?'Region':'Regionen'}`;
    $('results-title').textContent=state.favoritesOnly?'Meine Favoriten':state.query?'Suchergebnisse':state.region!=='all'?regions.find(r=>r.id===state.region).name:state.continent==='all'?'Alle Regionen':state.continent==='Fiktiv'?'Mt. Eddie / DLC':state.continent;
    const noFavorites=state.favoritesOnly&&!favorites.regions.size&&!favorites.mountains.size;
    $('empty').hidden=filtered.length>0;
    $('empty-title').textContent=noFavorites?'Deine Favoriten warten auf dich.':'Kein Drop gefunden.';
    $('empty-description').textContent=noFavorites?'Markiere eine Region oder einen Berg mit dem Stern. Hier findest du dann die dazugehörigen Level.':state.favoritesOnly?'Keine deiner Lieblingsstrecken passt zu den aktiven Filtern. Ändere die Suche oder zeige wieder alle Level.':'Versuche einen anderen Namen oder setze die Filter zurück.';
    favoritesInfo();
    $('cards').innerHTML=shown.map(r=>{
      const list=filtered.filter(l=>l.region===r),img=images[r.id];
      const mountainGroups=Object.keys(r.mountains).filter(m=>list.some(l=>l.mountain===m));
      const groups=mountainGroups.map(mountain=>`<section class="mountain-group" aria-label="${escape(mountain)}"><div class="mountain-heading"><h4>${highlight(mountain)}</h4>${star('mountains',mountainKey(r.id,mountain))}</div><ul class="level-list">${list.filter(l=>l.mountain===mountain).map(l=>`<li><button type="button" class="level-row" data-level="${l.id}" aria-label="${escape(l.name)} – ${escape(l.mountain)}: Details"><span class="level-number">${String(list.indexOf(l)+1).padStart(2,'0')}</span><span class="level-text"><span class="level-name">${highlight(l.name)}${r.deadly===l.name?'<span class="deadly-icon" title="Deadly Descent" aria-label="Deadly Descent">◆</span>':''}</span></span>${timeDisplay(l)}<span class="level-cue" aria-hidden="true">＋</span></button></li>`).join('')}</ul></section>`).join('');
      return `<article class="region-card"><div class="card-image">${picture(r)}<span class="image-label">${img?'SPIEL-SCREENSHOT':'SSX 2012'}</span>${star('regions',r.id,'region-star')}<div class="image-heading"><div><span class="continent-label">${escape(r.continent==='Fiktiv'?'Fiktive Region':r.continent)}</span><h3>${escape(r.name)}</h3></div><span class="level-pill">${list.length} Level</span></div></div>${img?`<div class="image-source"><span>${escape(img.shortCaption||'Regionsansicht')}</span><a href="${escape(img.source)}" target="_blank" rel="noopener noreferrer">Bildquelle ↗</a></div>`:''}<div class="card-info"><span>${Object.keys(r.mountains).length} ${Object.keys(r.mountains).length===1?'Berg':'Berge'} · ${escape(r.country)}</span><span class="tag ${r.content==='dlc'?'dlc':''}">${contentNames[r.content]}</span></div>${groups}<div class="card-end"><span class="dot" aria-hidden="true"></span>${r.hazard?`Deadly Descent · ${escape(r.hazard)}`:r.content==='dlc'?'5 Strecken · 9 Race- / Trick-Events':'Mount Fuji · ursprünglich PS3-exklusiv'}</div></article>`;
    }).join('');
    $('cards').querySelectorAll('img').forEach(img=>img.addEventListener('error',()=>{const note=document.createElement('div');note.className='fallback-picture';note.textContent='Bild nicht verfügbar · Quelle öffnen';img.replaceWith(note)},{once:true}));
  }
  function update(){options();navigation();render();}
  function reset(){Object.assign(state,{query:'',continent:'all',region:'all',mountain:'all',content:'all',favoritesOnly:false});$('search').value='';$('content').value='all';update();}
  function detail(id,trigger){const l=levels.find(l=>l.id===id);if(!l)return;const r=l.region,img=images[r.id];lastTrigger=trigger;$('detail-body').innerHTML=`${gallery(l,r)}${recordPanel(l)}<div class="detail-content"><div class="breadcrumbs">${escape(r.continent)} / ${escape(r.name)} / ${escape(l.mountain)}</div><h2 id="detail-title">${escape(l.name)}</h2><div class="detail-favorites"><div>${star('regions',r.id)}<span>Region merken</span></div><div>${star('mountains',mountainKey(r.id,l.mountain))}<span>Berg merken</span></div></div><dl class="detail-grid"><div><dt>Kontinent</dt><dd>${escape(r.continent==='Fiktiv'?'Fiktiv / nicht zugeordnet':r.continent)}</dd></div><div><dt>Region im Spiel</dt><dd>${escape(r.gameName)}</dd></div><div><dt>Berg</dt><dd>${escape(l.mountain)}</dd></div><div><dt>Spielinhalt</dt><dd>${contentNames[r.content]}</dd></div></dl><p>${escape(r.description)}</p>${r.deadly===l.name?`<p class="detail-note">◆ <strong>Deadly Descent: ${escape(r.hazard)}</strong><br>Ausrüstung: ${escape(r.gear)}.</p>`:l.name==='Death Zone'?'<p class="detail-note">World-Tour-Finale: Grudge Match gegen Griff an der Lhotse.</p>':r.content==='dlc'?`<p class="detail-note">Mt.-Eddie-Erweiterung. ${l.name==='The Kid’s Corner'?'Big-Air-Strecke mit Trick-Event.':'Race- und Trick-Event auf derselben Strecke.'}</p>`:''}<p class="detail-source">Streckenzuordnung: <a href="${r.content==='dlc'?sources.eddie:sources.tracks}" target="_blank" rel="noopener noreferrer">${r.content==='dlc'?'Mt.-Eddie-Streckenliste':'SSX Wiki'}</a>.</p></div>`;$('detail').showModal();startGallery();$('close-detail').focus();}
  function backupPayload(){return{format:backupFormat,version:1,exportedAt:new Date().toISOString(),favorites:{regions:[...favorites.regions],mountains:[...favorites.mountains]},records};}
  async function downloadBackup(){const filename='ssx-atlas-backup-'+new Date().toISOString().slice(0,10)+'.json',blob=new Blob([JSON.stringify(backupPayload(),null,2)],{type:'application/json'});if(window.showSaveFilePicker){try{const handle=await window.showSaveFilePicker({suggestedName:filename,types:[{description:'SSX Atlas Backup (JSON)',accept:{'application/json':['.json']}}]});const writable=await handle.createWritable();await writable.write(blob);await writable.close();$('backup-status').textContent='Backup gespeichert: '+handle.name;return;}catch(error){if(error.name==='AbortError'){$('backup-status').textContent='Speichern abgebrochen.';return;}}}const file=new File([blob],filename,{type:'application/json'});if(navigator.share&&navigator.canShare?.({files:[file]})){try{await navigator.share({files:[file],title:'SSX Atlas Backup',text:'Wähle „In Dateien sichern“, um dein Backup abzulegen.'});$('backup-status').textContent='Wähle im Teilen-Menü „In Dateien sichern“, um den Speicherort auszuwählen.';return;}catch(error){if(error.name==='AbortError'){$('backup-status').textContent='Speichern abgebrochen.';return;}}}const url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=filename;document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);$('backup-status').textContent='Backup-Download gestartet. Wähle den Speicherort im Browser-Dialog.';}
  function importBackup(payload){if(!payload||payload.format!==backupFormat||payload.version!==1)throw new Error('Das ist kein gültiges SSX-Atlas-Backup.');const incoming=sanitizeRecords(payload.records);for(const [id,values] of Object.entries(incoming)){const current=records[id]||{},merged={...current};if(values.raceMs!==undefined&&(merged.raceMs===undefined||values.raceMs<merged.raceMs))merged.raceMs=values.raceMs;if(values.survivalCm!==undefined&&(merged.survivalCm===undefined||values.survivalCm>merged.survivalCm))merged.survivalCm=values.survivalCm;if(values.trickPoints!==undefined&&(merged.trickPoints===undefined||values.trickPoints>merged.trickPoints))merged.trickPoints=values.trickPoints;for(const key of ['trickPointsDay','trickPointsNight'])if(values[key]!==undefined&&(merged[key]===undefined||values[key]>merged[key]))merged[key]=values[key];records[id]=merged;}const fav=payload.favorites||{};for(const id of Array.isArray(fav.regions)?fav.regions:[])if(favoriteNames.regions.has(id))favorites.regions.add(id);for(const id of Array.isArray(fav.mountains)?fav.mountains:[])if(favoriteNames.mountains.has(id))favorites.mountains.add(id);saveFavorites();const saved=saveRecords();update();$('backup-status').textContent=saved?'Backup importiert. Vorhandene Rekorde wurden mit den besseren Werten ergänzt.':'Backup geladen; Speichern ist in diesem Browser nicht verfügbar.';}
  $('export-backup').addEventListener('click',downloadBackup);$('import-backup').addEventListener('click',()=>$('backup-file').click());$('backup-file').addEventListener('change',async e=>{const file=e.target.files?.[0];if(!file)return;try{importBackup(JSON.parse(await file.text()));}catch(error){$('backup-status').textContent=error instanceof SyntaxError?'Die JSON-Datei ist beschädigt oder ungültig.':error.message||'Backup konnte nicht importiert werden.';}finally{e.target.value='';}});
  $('search').addEventListener('input',e=>{state.query=e.target.value;render()});
  ['region','mountain','content'].forEach(key=>$(key).addEventListener('change',e=>{state[key]=e.target.value;if(key==='content')state.region=state.mountain='all';if(key==='region')state.mountain='all';update()}));
  $('continents').addEventListener('click',e=>{const b=e.target.closest('[data-continent]');if(b){state.continent=b.dataset.continent;state.region=state.mountain='all';update()}});
  $('cards').addEventListener('click',e=>{const favorite=e.target.closest('[data-favorite-kind]');if(favorite){toggleFavorite(favorite);return;}const b=e.target.closest('[data-level]');if(b)detail(b.dataset.level,b)});
  $('detail-body').addEventListener('click',e=>{const favorite=e.target.closest('[data-favorite-kind]');if(favorite){toggleFavorite(favorite);return;}const toggle=e.target.closest('[data-record-toggle]');if(toggle){const form=$('detail-body').querySelector('[data-record-form]');form.hidden=!form.hidden;if(!form.hidden)form.querySelector('input').focus();startGallery();return;}const root=e.target.closest('[data-gallery]');if(!root)return;const counter=root.querySelector('[data-gallery-counter]');const index=counter?Number(counter.textContent.split(' ')[0]):1;if(e.target.closest('[data-gallery-prev]'))showGallerySlide(index-2);else if(e.target.closest('[data-gallery-next]'))showGallerySlide(index);else{const dot=e.target.closest('[data-gallery-dot]');if(dot)showGallerySlide(Number(dot.dataset.galleryDot));}startGallery();});
  function renderRaceEntry(input,raw){input.dataset.raw=raw;const parts=raw.split(',');const digits=(parts[0]||'').replace(/\D/g,'').slice(0,5);if(!digits){input.value=parts.length>1?',':'';return;}const padded=digits.padStart(4,'0'),minutes=padded.slice(0,-2),seconds=padded.slice(-2);input.value=minutes+':'+seconds+(parts.length>1?','+(parts[1]||'').slice(0,2):'');input.setSelectionRange(input.value.length,input.value.length);}
  $('detail-body').addEventListener('focus',e=>{const input=e.target.closest('[data-record-field="raceMs"]');if(input&&!input.dataset.raw)input.dataset.raw=input.value.replace(':','');},true);
  $('detail-body').addEventListener('beforeinput',e=>{const input=e.target.closest('[data-record-field="raceMs"]');if(!input||!e.cancelable)return;const data=e.data;if(e.inputType==='insertText'&&data!==null){if(!/^[0-9,:.]$/.test(data))return;e.preventDefault();let raw=input.dataset.raw||input.value.replace(':','');if(input.selectionStart!==input.selectionEnd)raw='';if(data===':'||data==='.')return;if(data===','){if(!raw.includes(','))raw+=',';}else if(raw.includes(',')){const parts=raw.split(',');if(parts[1].length<2)raw=parts[0]+','+parts[1]+data;}else if(raw.replace(/\D/g,'').length<5)raw+=data;renderRaceEntry(input,raw);return;}if(e.inputType==='deleteContentBackward'){e.preventDefault();let raw=input.dataset.raw||input.value.replace(':','');raw=raw.endsWith(',')?raw.slice(0,-1):raw.slice(0,-1);renderRaceEntry(input,raw);}});
  $('detail-body').addEventListener('input',e=>{const input=e.target.closest('[data-record-field="raceMs"]');if(!input||input.dataset.raw)return;const raw=input.value.replace(':','');if(!/^\d{0,5}(?:,\d{0,2})?$/.test(raw))return;renderRaceEntry(input,raw);});
  $('detail-body').addEventListener('focusout',e=>{const input=e.target.closest('[data-record-field]');if(!input||!input.value.trim())return;let parsed;if(input.dataset.recordField==='raceMs')parsed=parseRaceInput(input.value);else if(input.dataset.recordField==='survivalCm')parsed=parseMetersInput(input.value);else parsed=parsePointsInput(input.value);if(parsed){input.value=parsed.formatted;input.removeAttribute('aria-invalid');}else input.setAttribute('aria-invalid','true');});
  $('detail-body').addEventListener('submit',e=>{const form=e.target.closest('[data-record-form]');if(!form)return;e.preventDefault();const status=form.querySelector('.record-status'),level=levels.find(l=>l.id===form.dataset.recordLevelId);if(!level)return;const next={...(records[level.id]||{})};let changed=false;for(const input of form.querySelectorAll('[data-record-field]')){if(!input.value.trim())continue;const kind=input.dataset.recordField;let parsed;if(kind==='raceMs')parsed=parseRaceInput(input.value);else if(kind==='survivalCm')parsed=parseMetersInput(input.value);else parsed=parsePointsInput(input.value);if(!parsed){status.textContent=kind==='raceMs'?'Bitte gib Rennen als 0053,25 oder 00:53,25 ein.':kind==='survivalCm'?'Bitte gib Überleben als Meter mit Komma ein, zum Beispiel 11876,24.':'Bitte gib Tricky als Punktzahl ein, zum Beispiel 54333300.';input.setAttribute('aria-invalid','true');input.focus();return;}next[kind]=kind==='raceMs'?parsed.ms:kind==='survivalCm'?parsed.cm:parsed.points;input.value=parsed.formatted;input.removeAttribute('aria-invalid');delete input.dataset.raw;changed=true;}if(!changed){status.textContent='Trage mindestens einen neuen Rekord ein.';return;}records[level.id]=next;const persisted=saveRecords();render();status.textContent=persisted?'Deine Rekorde wurden auf diesem Gerät gespeichert.':'Speichern ist nicht verfügbar; die Rekorde bleiben bis zum Neuladen erhalten.';});
  $('favorites-filter').addEventListener('click',()=>{state.favoritesOnly=!state.favoritesOnly;render()});
  window.addEventListener('storage',e=>{if(e.key===storageKey||e.key===null){readFavorites();render();if($('detail').open){$('detail-body').querySelectorAll('[data-favorite-kind]').forEach(b=>{b.outerHTML=star(b.dataset.favoriteKind,b.dataset.favoriteKey)});}}if(e.key===recordStorageKey||e.key===null){readRecords();render();if($('detail').open){const levelId=$('detail-body').querySelector('[data-gallery]')?.dataset.levelId,values=records[levelId]||{};const form=$('detail-body').querySelector('[data-record-form]');form?.querySelectorAll('[data-record-field]').forEach(input=>{const key=input.dataset.recordField,value=values[key];if(value===undefined)return;input.value=key==='raceMs'?formatShortRace(value):key==='survivalCm'?formatMeters(value).replace(/ m$/,''):formatPoints(value);});}}});
  $('reset').addEventListener('click',reset);$('empty-reset').addEventListener('click',reset);$('close-detail').addEventListener('click',()=>$('detail').close());$('detail').addEventListener('click',e=>{if(e.target===$('detail')){const box=$('detail').getBoundingClientRect();if(e.clientX<box.left||e.clientX>box.right||e.clientY<box.top||e.clientY>box.bottom)$('detail').close()}});$('detail').addEventListener('close',()=>{stopGallery();const target=lastTrigger?.isConnected?lastTrigger:[...$('cards').querySelectorAll('[data-level]')].find(b=>b.dataset.level===lastTrigger?.dataset.level);(target||$('favorites-filter')).focus({preventScroll:true})});
  document.addEventListener('keydown',e=>{if(e.key==='/'&&!['INPUT','SELECT','TEXTAREA'].includes(document.activeElement.tagName)&&!$('detail').open){e.preventDefault();$('search').focus()}});
  $('total-levels').textContent=levels.length;update();
  if(document.modelContext?.registerTool){
    const lifecycle=new AbortController();
    const tool={name:'search_ssx_levels',title:'SSX-Level suchen',description:'Sucht SSX-Level und zeigt die Ergebnisse mit Kontinent-, Regions- und Inhaltsfilter im Atlas.',inputSchema:{type:'object',properties:{query:{type:'string'},continent:{type:'string',enum:['all',...continents]},content:{type:'string',enum:['all','base','bonus','dlc']}},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).some(k=>!['query','continent','content'].includes(k))||(input.query!==undefined&&typeof input.query!=='string')||(input.continent!==undefined&&!['all',...continents].includes(input.continent))||(input.content!==undefined&&!['all','base','bonus','dlc'].includes(input.content)))throw new Error('Ungültige Suchparameter.');Object.assign(state,{query:input.query||'',continent:input.continent||'all',content:input.content||'all',region:'all',mountain:'all',favoritesOnly:false});$('search').value=state.query;$('content').value=state.content;update();return{count:filtered.length,levels:filtered.map(l=>({name:l.name,mountain:l.mountain,region:l.region.name,continent:l.region.continent}))};}};
    try{Promise.resolve(document.modelContext.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}
    window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});
  }
})();
