// Levelnamen und Zuordnungen: SSX Wiki; World Tour: BenDstraw (GameFAQs).
// Ein Level wird einmal gezählt, unabhängig von seinen Race-/Trick-/Survive-Events.
window.SSX_REGIONS = [
  { id:'rockies', name:'Rocky Mountains', gameName:'Rockies', continent:'Nordamerika', country:'Kanada', content:'base', hazard:'Bäume', deadly:'Intrepid', gear:'Körperpanzer', description:'Waldabfahrten und felsige Gipfel in den kanadischen Rockies.', mountains:{'Whitehorn Mountain':["Curnoe’s Moustache",'JT2'],'Extinguisher Tower':['Broken Tooth','The Dagger','Wrecking Crew'],'Mount Robson':['Intrepid']} },
  { id:'alaska', name:'Alaska', gameName:'Alaska', continent:'Nordamerika', country:'USA', content:'base', hazard:'Lawinen', deadly:'Emergency Exit', gear:'Körperpanzer', description:'Weite Schneefelder und die Lawinenabfahrt am Denali.', mountains:{'Silverthrone':['Old School','Pan','Unsanctioned'],'Foraker':['Invincible','Lock Jaw','The Dilemma'],'Denali':['Emergency Exit']} },
  { id:'alps', name:'Alpen', gameName:'Alps', continent:'Europa', country:'Frankreich / Italien', content:'base', hazard:'Felsen', deadly:'One Way Ticket', gear:'Körperpanzer', description:'Enge Felspassagen rund um Mont Blanc und Grand Golliat.', mountains:{'Vorassay':['Beyond the Fall','Broken Pass','The Hammer'],'Grand Golliat':['Hard Currency','One Step Ahead','Wächter'],'Mont Blanc':['One Way Ticket']} },
  { id:'himalayas', name:'Himalaya', gameName:'Himalayas', continent:'Asien', country:'Nepal / China', content:'base', hazard:'Dünne Luft', deadly:'Burnout', gear:'Sauerstofftank', description:'Hochgebirge, lange Abfahrten und das Finale an der Lhotse.', mountains:{'Makalu':['Fast Forward','Serenity','Trickypedia'],'Chomo Lonzo':['Bear Claw','Fall from Grace','The Monster'],'Mount Everest':['Burnout'],'Lhotse':['Death Zone']} },
  { id:'siberia', name:'Sibirien', gameName:'Siberia', continent:'Asien', country:'Russland', content:'base', hazard:'Eis', deadly:'Punch Up', gear:'Eispickel', description:'Eisige Hänge und industrielle Hindernisse im Altai.', mountains:{'Boris':['Diamond Back','The Big Show','Vapor Trail'],'Kara-Oiuk':['Critical Mass','Don’t Make Me'],'Mount Belukha East':['Punch Up']} },
  { id:'japan', name:'Japan', gameName:'Japan', continent:'Asien', country:'Japan', content:'bonus', description:'Drei Abfahrten am Mount Fuji. Ursprünglich ein PS3-Bonus.', mountains:{'Mount Fuji':['99 Assassins','Area Zero','Home Run']} },
  { id:'patagonia', name:'Patagonien', gameName:'Patagonia', continent:'Südamerika', country:'Argentinien / Chile', content:'base', hazard:'Abgründe', deadly:'Broken Elbow', gear:'Wingsuit', description:'Steile Granitwände und große Sprünge zwischen den Gipfeln.', mountains:{'Cerro Pollone':['Blackbox','Majestic','Salient','Weirdsville'],'Cerro Torre':['Code Blue','Last Call','Vengeance'],'Fitz Roy':['Broken Elbow']} },
  { id:'africa', name:'Afrika', gameName:'Africa', continent:'Afrika', country:'Tansania', content:'base', hazard:'Dunkelheit', deadly:'Snake Bite', gear:'Stirnlampe', description:'Vulkanische Abfahrten und dunkle Tunnel am Kilimanjaro.', mountains:{'Meru':['Corkscrew','Red Light'],'Mawenzi':['Hush','Incoming'],'Kilimanjaro':['Snake Bite']} },
  { id:'new-zealand', name:'Neuseeland', gameName:'New Zealand', continent:'Ozeanien', country:'Neuseeland', content:'base', hazard:'Whiteout', deadly:'Route Zero', gear:'Impulsbrille', description:'Abfahrten in den Südalpen bis zum Whiteout am Aoraki.', mountains:{'Mount Wakefield':['Bulldog','Last to Hit','Mornin’ Tiger','Zombies with Jetpacks'],'Mount Tasman':['Buckeye','Jack-Knife','Thunderbird'],'Aoraki':['Route Zero']} },
  { id:'antarctica', name:'Antarktis', gameName:'Antarctica', continent:'Antarktika', country:'Antarktis', content:'base', hazard:'Kälte', deadly:'Dreadnought', gear:'Kälteschutz', description:'Abgelegenes Eisgebirge mit eisiger Kälte im Schatten.', mountains:{'Vinson Massif':['Evil Genius','Off the Grid','Rolling Thunder'],'Mount Craddock':['Headshot','Long Horn','Root Down'],'Mount Slaughter':['Dreadnought']} },
  { id:'eddie', name:'Mt. Eddie', gameName:'Mount Eddie', continent:'Fiktiv', country:'Kein realer Kontinent', content:'dlc', description:'Retro-Strecken aus dem Mt.-Eddie-DLC: fünf Level mit neun Race-/Trick-Events.', mountains:{'Eddie’s Peak':['The Big Wachowski','Fro with the Flow','Slipped Disco','The Kid’s Corner','Luge Your Way']} }
];
window.SSX_SOURCES = {
  tracks:'https://ssx.fandom.com/wiki/SSX_%282012%29%27s_Tracks',
  guide:'https://gamefaqs.gamespot.com/ps3/615810-ssx/faqs/63954',
  eddie:'https://gamefaqs.gamespot.com/boards/615811-ssx/62686310',
  dlc:'https://www.ea.com/de-de/news/ssx-classic-dlc-jetzt-erhaeltlich'
};
